### PR TITLE
Don't hard-code CPU ids

### PR DESCRIPTION
**Pull request by rsdy**
Under the current code, CPU ids are hard-coded, which means that if a system has less than 4 cores, the process will fail with:

```
perf_event_open: No such device
   (check your kernel for PERF_COUNT_SW_BPF_OUTPUT support, 4.4 or newer)
Error: failed to open perf buffer
```

This patch fixes the hard-coded CPU issue, and creates a perf event listener for every single CPU individually.

I'm still not sure if this is the right thing to do here, as the [man page](http://man7.org/linux/man-pages/man2/perf_event_open.2.html) has the following snippet about the `cpu` parameter:

> pid == 0 and cpu == -1
>        This measures the calling process/thread on any CPU. 

So simply passing `-1` as the CPU value would feasibly achieve the same thing. I have not explored this further, but considering the number of options passed to the syscall, it might be reasonable to expose some more control here in an idiomatic way.

### CODE REVIEW

**Comment by jvns** [comment]
Thanks for working on this! This is probably the most glaring bug in rust-bcc right now :) 

I'm happy to merge this because it's definitely an improvement, but I think there's a more accurate way to do this as well.

It looks like the `num_cpus` crate uses /proc/cpuinfo to count the number of CPUs. I think it would be better to use `/sys/devices/system/cpu/online` instead because my understanding is it's possible for CPUs to be numbered nonconsecutively

the corresponding code in the Go BPF library( https://github.com/iovisor/gobpf/blob/9ea8fb24d6dc7fb142175a5b80f037633124d453/pkg/cpuonline/cpu_range.go) parses /sys/devices/system/cpu/online

**Comment by rsdy** [comment]
Oh, sorry for failing to get back on this. I was meaning to make the changes you recommended, as they definitely make sense, I've just been struggling to find the time to get back to this. If you want I can still make the changes, I'm hoping I'll be able to carve out some time for this next week!

**Comment by photoszzt** [comment]
Maybe it's late to mention this but I port the go bpf cpuonline(https://github.com/photoszzt/rust-bpf/blob/master/src/cpuonline/cpuonline.rs) library to Rust in by rust-bpf port. If you want to use it, I can give you a PR or maybe I can make it a crate. But I'm not sure whether it's worth to be a separate crate on crates.io.

**Comment by jvns** [comment]
@photoszzt a PR would be great!

**Pull request merged**
